=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_XSD/Ejercicio06/birthday.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="birthdays">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="family" type="family" />
                <xs:element name="friends" type="friends" />
                <xs:element name="colleagues" type="colleagues" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="friends">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="friend" type="birthday" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="colleagues">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="colleague" type="birthday" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="family">
        <xs:sequence>
            <xs:element name="mother" type="birthday" />
            <xs:element name="father" type="birthday" />
            <xs:choice>
                <xs:element name="husband" type="birthday" />
                <xs:element name="wife" type="birthday" />
            </xs:choice>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="sister" type="birthday" />
                <xs:element name="brother" type="birthday" />
                <xs:element name="son" type="birthday" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="birthday">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="date" type="xs:date" />
            <xs:element ref="phone" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
    <xs:element name="phone">
        <xs:complexType>
            <xs:attribute name="number" type="xs:integer" />
            <xs:attribute name="network" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="MEO" />
                        <xs:enumeration value="ZON" />
                        <xs:enumeration value="Vodafone" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_XSD/Ejercicio06/birthday.xml
<?xml version="1.0" encoding="UTF-8"?>
<birthdays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="birthday.xsd">
    <family>
        <mother name="Pilar">
            <date>1969-03-13</date>
            <phone network="Vodafone" />
        </mother>
        <father name="Jesús">
            <date>1963-05-14</date>
            <phone network="ZON" />
        </father>
        <husband name="Miguel">
            <date>1998-06-01</date>
            <phone network="MEO" />
        </husband>
        <brother name="David">
            <date>2002-05-30</date>
            <phone network="Vodafone" />
        </brother>
    </family>
    <friends>
        <friend name="Álvaro">
            <date>2002-02-05</date>
            <phone network="ZON" />
        </friend>
    </friends>
    <colleagues>
        <colleague name="Juan Carlos">
            <date>1968-09-08</date>
            <phone network="MEO" />
        </colleague>
    </colleagues>
</birthdays>
