=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_XSD/Ejercicio07/trenes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="stations">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="station" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="locationX" type="xs:decimal" use="required" />
                                <xs:attribute name="locationY" type="xs:decimal" use="required" />
                                <xs:attribute name="id" type="xs:ID" use="required" />
                                <xs:attribute name="URI" use="required" />
                                <xs:attribute name="standardname" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:decimal" use="required" />
            <xs:attribute name="timestamp" type="xs:integer" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_XSD/Ejercicio07/trenes.xml
<stations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="trenes.xsd" version="1.1" timestamp="1645094935">
<station locationX="4.32571361" locationY="51.2191923" id="BE.NMBS.000000101" URI="http://irail.be/stations/NMBS/000000101" standardname="Zwijndrecht Dorp">Zwijndrecht Dorp</station>
<station locationX="0.12380800" locationY="51.5304000" id="BE.NMBS.007015400" URI="http://irail.be/stations/NMBS/007015400" standardname="London Saint Pancras International">London Saint Pancras International</station>
<station locationX="0.27577500" locationY="51.4511700" id="BE.NMBS.007015440" URI="http://irail.be/stations/NMBS/007015440" standardname="Ebbsfleet International">Ebbsfleet International</station>
<station locationX="6.795297" locationY="51.219178" id="BE.NMBS.008008094" URI="http://irail.be/stations/NMBS/008008094" standardname="Duesseldorf Hbf">Dusseldorf Hbf</station>
<station locationX="7.459293" locationY="51.517898" id="BE.NMBS.008010053" URI="http://irail.be/stations/NMBS/008010053" standardname="Dortmund Hbf">Dortmund Hbf</station>
<station locationX="6.77611800" locationY="51.4295200" id="BE.NMBS.008010184" URI="http://irail.be/stations/NMBS/008010184" standardname="Essen Hbf">Essen Hbf</station>
<station locationX="6.7759037" locationY="51.42978" id="BE.NMBS.008010316" URI="http://irail.be/stations/NMBS/008010316" standardname="Duisburg Hbf">Duisburg Hbf</station>
<station locationX="8.6653708" locationY="50.1071318" id="BE.NMBS.008011068" URI="http://irail.be/stations/NMBS/008011068" standardname="Frankfurt am Main Hbf">Frankfurt am Main Hbf</station>
<station locationX="8.569853" locationY="50.051696" id="BE.NMBS.008011090" URI="http://irail.be/stations/NMBS/008011090" standardname="Frankfurt am Main Flughafen Reginalbf">Frankfurt am Main Flughafen Reginalbf</station>
<station locationX="6.105275" locationY="50.770832" id="BE.NMBS.008015345" URI="http://irail.be/stations/NMBS/008015345" standardname="Aachen Hbf">Aachen Hbf</station>
<station locationX="6.958823" locationY="50.942721" id="BE.NMBS.008015458" URI="http://irail.be/stations/NMBS/008015458" standardname="Köln Hbf">Köln Hbf</station>
<station locationX="7.203029" locationY="50.793916" id="BE.NMBS.008015588" URI="http://irail.be/stations/NMBS/008015588" standardname="Siegburg">Siegburg</station>
<station locationX="6.76705200" locationY="51.2765600" id="BE.NMBS.008015653" URI="http://irail.be/stations/NMBS/008015653" standardname="Duesseldorf Flughafen (DE)">Duesseldorf Flughafen (DE)</station>
<station locationX="8.06326100" locationY="50.3842000" id="BE.NMBS.008032572" URI="http://irail.be/stations/NMBS/008032572" standardname="Limburg Süd">Limburg Süd</station>
<station locationX="6.786837" locationY="51.292008" id="BE.NMBS.008039904" URI="http://irail.be/stations/NMBS/008039904" standardname="Düsseldorf Flughafen Hbf">Düsseldorf Flughafen Hbf</station>
<station locationX="8.66361100" locationY="50.1308300" id="BE.NMBS.008061676" URI="http://irail.be/stations/NMBS/008061676" standardname="Frankfurt am Main Flughafen Fernbf">Frankfurt am Main Flughafen Fernbf</station>
<station locationX="16.375864" locationY="48.184923" id="BE.NMBS.008101003" URI="http://irail.be/stations/NMBS/008101003" standardname="Wien Hbf">Vienna Main Station</station>
<station locationX="6.133331" locationY="49.599996" id="BE.NMBS.008200100" URI="http://irail.be/stations/NMBS/008200100" standardname="Lëtzebuerg">Lëtzebuerg</station>
<station locationX="6.13668" locationY="49.633838" id="BE.NMBS.008200101" URI="http://irail.be/stations/NMBS/008200101" standardname="Dommeldange">Dommeldange</station>
<station locationX="6.13285300" locationY="49.6191260" id="BE.NMBS.008200102" URI="http://irail.be/stations/NMBS/008200102" standardname="Pfaffenthal-Kirchberg">Pfaffenthal-Kirchberg</station>
<station locationX="6.106111" locationY="49.748893" id="BE.NMBS.008200110" URI="http://irail.be/stations/NMBS/008200110" standardname="Mersch">Mersch</station>
<station locationX="6.104169" locationY="49.847496" id="BE.NMBS.008200120" URI="http://irail.be/stations/NMBS/008200120" standardname="Ettelbréck">Ettelbréck</station>
<station locationX="6.09149000" locationY="49.8972900" id="BE.NMBS.008200128" URI="http://irail.be/stations/NMBS/008200128" standardname="Michelau">Michelau</station>
<station locationX="49.92104" locationY="6.053335" id="BE.NMBS.008200129" URI="http://irail.be/stations/NMBS/008200129" standardname="Goebelsmühle">Goebelsmühle</station>
<station locationX="6.020003" locationY="49.952777" id="BE.NMBS.008200130" URI="http://irail.be/stations/NMBS/008200130" standardname="Kautebaach">Kautebaach</station>
<station locationX="5.999166" locationY="49.988887" id="BE.NMBS.008200132" URI="http://irail.be/stations/NMBS/008200132" standardname="Wilwerwiltz">Wilwerwiltz</station>
<station locationX="6.006106" locationY="50.017778" id="BE.NMBS.008200133" URI="http://irail.be/stations/NMBS/008200133" standardname="Drauffelt">Drauffelt</station>
<station locationX="6.031393" locationY="50.054724" id="BE.NMBS.008200134" URI="http://irail.be/stations/NMBS/008200134" standardname="Clervaux">Clervaux</station>
<station locationX="6.000281" locationY="50.121109" id="BE.NMBS.008200136" URI="http://irail.be/stations/NMBS/008200136" standardname="Troisvierges">Troisvierges</station>
<station locationX="6.060601" locationY="49.613002" id="BE.NMBS.008200510" URI="http://irail.be/stations/NMBS/008200510" standardname="Bertrange Strassen">Bertrange Strassen</station>
<station locationX="6.02014" locationY="49.625663" id="BE.NMBS.008200516" URI="http://irail.be/stations/NMBS/008200516" standardname="Mamer">Mamer</station>
<station locationX="5.99083300" locationY="49.6450000" id="BE.NMBS.008200518" URI="http://irail.be/stations/NMBS/008200518" standardname="Capellen">Capellen</station>
<station locationX="5.916385" locationY="49.646389" id="BE.NMBS.008200520" URI="http://irail.be/stations/NMBS/008200520" standardname="Klengbetten">Klengbetten</station>
<station locationX="5.87868100" locationY="49.5542500" id="BE.NMBS.008200930" URI="http://irail.be/stations/NMBS/008200930" standardname="Petange">Petange</station>
<station locationX="5.845028" locationY="49.551283" id="BE.NMBS.008200940" URI="http://irail.be/stations/NMBS/008200940" standardname="Rodange">Rodange</station>
<station locationX="6.02968" locationY="49.618415" id="BE.NMBS.008210014" URI="http://irail.be/stations/NMBS/008210014" standardname="Mamer-Lycée">Mamer-Lycée</station>
<station locationX="4.91666700" locationY="52.3500000" id="BE.NMBS.008400058" URI="http://irail.be/stations/NMBS/008400058" standardname="Amsterdam CS">Amsterdam CS</station>
<station locationX="4.7764000000" locationY="51.5944590000" id="BE.NMBS.008400131" URI="http://irail.be/stations/NMBS/008400131" standardname="Breda">Breda</station>
<station locationX="4.666668" locationY="51.799998" id="BE.NMBS.008400180" URI="http://irail.be/stations/NMBS/008400180" standardname="Dordrecht">Dordrecht</station>
<station locationX="5.709786" locationY="50.772135" id="BE.NMBS.008400219" URI="http://irail.be/stations/NMBS/008400219" standardname="Eijsden">Eijsden</station>
<station locationX="4.299999" locationY="52.083329" id="BE.NMBS.008400280" URI="http://irail.be/stations/NMBS/008400280" standardname="Den Haag HS">Den Haag HS</station>
<station locationX="5.70539200" locationY="50.8500000" id="BE.NMBS.008400424" URI="http://irail.be/stations/NMBS/008400424" standardname="Maastricht">Maastricht</station>
<station locationX="5.716707" locationY="50.838502" id="BE.NMBS.008400426" URI="http://irail.be/stations/NMBS/008400426" standardname="Maastricht Randwyck">Maastricht Randwyck</station>
<station locationX="4.45869200" locationY="51.5408340" id="BE.NMBS.008400526" URI="http://irail.be/stations/NMBS/008400526" standardname="Roosendaal">Roosendaal</station>
<station locationX="4.50000000" locationY="51.9166670" id="BE.NMBS.008400530" URI="http://irail.be/stations/NMBS/008400530" standardname="Rotterdam CS">Rotterdam CS</station>
<station locationX="4.75000000" locationY="52.3000000" id="BE.NMBS.008400561" URI="http://irail.be/stations/NMBS/008400561" standardname="Schiphol">Schiphol</station>
<station locationX="7.590716" locationY="47.547408" id="BE.NMBS.008500010" URI="http://irail.be/stations/NMBS/008500010" standardname="Basel">Basel</station>
<station locationX="2.782184" locationY="48.868256" id="BE.NMBS.008711184" URI="http://irail.be/stations/NMBS/008711184" standardname="Marne-la-Vallée - Chessy">Marne-la-Vallée - Chessy</station>
<station locationX="6.16972200" locationY="48.9475000" id="BE.NMBS.008714210" URI="http://irail.be/stations/NMBS/008714210" standardname="Lorraine TGV">Lorraine TGV</station>
<station locationX="7.366668" locationY="48.083335" id="BE.NMBS.008718201" URI="http://irail.be/stations/NMBS/008718201" standardname="Colmar">Colmar</station>
<station locationX="7.333336" locationY="47.749998" id="BE.NMBS.008718206" URI="http://irail.be/stations/NMBS/008718206" standardname="Mulhouse">Mulhouse</station>
<station locationX="7.555316" locationY="47.5907" id="BE.NMBS.008718213" URI="http://irail.be/stations/NMBS/008718213" standardname="Saint-Louis-Haut-Rhin">Saint-Louis-Haut-Rhin</station>
<station locationX="6.166663" locationY="49.366663" id="BE.NMBS.008719100" URI="http://irail.be/stations/NMBS/008719100" standardname="Thionville">Thionville</station>
<station locationX="6.166663" locationY="49.13333" id="BE.NMBS.008719203" URI="http://irail.be/stations/NMBS/008719203" standardname="Metz">Metz</station>
<station locationX="7.733905" locationY="48.585437" id="BE.NMBS.008721202" URI="http://irail.be/stations/NMBS/008721202" standardname="Strasbourg">Strasbourg</station>
<station locationX="7.362255" locationY="48.744798" id="BE.NMBS.008721222" URI="http://irail.be/stations/NMBS/008721222" standardname="Saverne">Saverne</station>
