=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_XSD/Ejercicio01/estudiante.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="estudiante">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"></xs:element>
                <xs:element name="apellidos" type="xs:string"></xs:element>
                <xs:element name="id" type="xs:int"></xs:element>
                <xs:element name="plan">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cursos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="curso" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="nombre_corto" type="xs:string"></xs:element>
                                                    <xs:element name="registro" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="grado" type="xs:int"></xs:element>
                                                                <xs:element name="fecha" type="xs:string"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="anyo" type="xs:int"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_XSD/Ejercicio01/estudiante.xml
<?xml version="1.0" encoding="UTF‐8"?>
<estudiante xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="estudiante.xsd">
    <nombre>Luca</nombre>
    <apellidos>Rossi</apellidos>
    <id>281283</id>
    <plan>
        <cursos anyo="3">
            <curso>
                <nombre>Programacion Orientada a Objetos</nombre>
                <nombre_corto>POO</nombre_corto>
                <registro>
                    <grado>30</grado>
                    <fecha>13/06/11</fecha>
                </registro>
            </curso>
            <curso>
                <nombre>Analisis del software</nombre>
                <nombre_corto>AS</nombre_corto>
            </curso>
        </cursos>
    </plan>
</estudiante>
