=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_DTD/Ejercicio02/seguridad_social.dtd
<!ELEMENT lista_afiliados (afiliado*)>
    <!ELEMENT afiliado (dni, nombre, apellidos, fecha_nac, listado_bajas, listado_presentaciones)>
        <!ATTLIST afiliado situacion_laboral (en_paro|en_activo|jubilado|edad_no_laboral) #REQUIRED>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT situacion_laboral (#PCDATA)>
    <!ELEMENT fecha_nac (dia, mes, anio)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
    <!ELEMENT listado_bajas (baja*)>
    <!ELEMENT baja (causa, fecha_inicio, fecha_final?)>
    <!ELEMENT causa (#PCDATA)>
    <!ELEMENT fecha_inicio (#PCDATA)>
    <!ELEMENT fecha_final (#PCDATA)>
    <!ELEMENT listado_presentaciones (prestacion*)>
    <!ELEMENT prestacion (cantidad_percibida, fecha_inicio, fecha_final)>
    <!ELEMENT cantidad_percibida (#PCDATA)>

=== gonzsanz/Lenguaje-de-Marcas/PRACTICAS/PRACTICA_DTD/Ejercicio02/seguridad_social.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_afiliados SYSTEM "seguridad_social.dtd">

<lista_afiliados>
    <afiliado situacion_laboral="edad_no_laboral">  <!-- en paro, en activo, jubilado, edad no laboral -->
        <dni>11655543T</dni>
        <nombre>Alfredo</nombre>
        <apellidos>Duro Rodrígez</apellidos>
        <fecha_nac>
            <!-- Obligatorio-->
            <dia>31</dia>
            <mes>05</mes>
            <anio>1978</anio>
        </fecha_nac>
        <listado_bajas>
            <!-- Puede haber 0 o más-->
            <baja>
                <causa>Lesión dedo meñique de la mano</causa> <!-- Obligatorio-->
                <fecha_inicio>17-05-2013</fecha_inicio> <!-- Obligatorio-->
                <fecha_final>26-05-2013</fecha_final> <!-- Opcional-->
            </baja>
        </listado_bajas>
        <listado_presentaciones>
            <prestacion>
                <!-- Puede haber 0 o más-->
                <cantidad_percibida>267€</cantidad_percibida> <!-- Obligatorio -->
                <fecha_inicio>20-05-2013</fecha_inicio> <!-- Obligatorio-->
                <fecha_final>27-05-2013</fecha_final> <!-- Obligatorio-->
            </prestacion>
        </listado_presentaciones>
    </afiliado>
</lista_afiliados>
